# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26aec1c5c696bc23f9d1ce34153053bc717da97a523773ec535545eda75a069fac1cb3add89707ac0c4862aefd845d92a51c7ec1d095aa0e2793b3738357eb73

test:
  secret_key_base: b1a3fa303ba8fb97489c7480f33d449b668236ba230e194e22012ab24fbb0fe0551bdece21feb9394d0108858a4adfb898a82a015f88d071f7086537b2efa1b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
